DEBUG = True
SQLALCHEMY_TRACK_MODIFICATIONS = False
BCRYPT_LOG_ROUNDS = 15
SGF_FOLDER = '/home/guyu/kifutalk/app/static/assets/sgf'
THUMBNAIL_FOLDER = '/home/guyu/kifutalk/app/static/assets/thumbnail'
EMPTY_BOARD_DATAURL = '/home/guyu/kifutalk/app/static/assets/empty_board.dataurl'
PERPAGE = 5
THUMBNAIL_SIZE = (512, 512)
URL_TIMEOUT = 10 # seconds
